version: 2.1
jobs:
  build_docker:
    docker:
      - image: cimg/python:3.9.16
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
  clone_appdome_api:
    steps:
      - run:
          name: Clone appfome api repository
          command: |
            git clone https://github.com/Appdome/appdome-api-python.git
            ls -al
  install_requirments:
    steps:
       - run:
          name: Install python requirments
          command: |
            pip3 install -r /appdome-api-python/requirements.txt
workflows:
  nir_workflow:
    jobs:
      - build_docker
      - clone_appdome_api
      - install_requirments
