version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
        - name: Cloning appdome-api-python github repository
            uses: actions/checkout@master
            with:
              repository: Appdome/appdome-api-python
              ref: refs/heads/main
              path: appdome
      - run:
          name: The Second Step
          command: |
            ls -al
            echo '----- The files in your repro -----'
