# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@1.2.6
jobs:
  build_and_test: #This can be any name
    executor: python/default
    steps:
    - checkout
    - python/install-packages:
      pkg-manager: pip
     - run:
        name: Run tests
        command: python -m pytest
     - persist_to_workspace:
        root: ~/project
        paths:
          - .
    deploy: #This can be any name
      executor: heroku/default
      steps:
        - attach_workspace:
          at: ~/project
        - heroku/deploy-via-git:
        force: true
workflows:
  build_test_deploy: #this can be any name
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main
    
