version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.9.16
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Clone Appdome API repository
          command: |
            git clone https://github.com/Appdome/appdome-api-python.git
            ls -al
            cd ./appdome-api-pythom
            pip3 install -r ./requirements.txt
      - run:
          name: Install requirments
          command: |
            ls -al
